### PR TITLE
Add ability to set default value for an attribute.

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
We were facing problems in upgrading to Rails 4 due to changes here - https://gist.github.com/mohitnatoo/fbf608799586f4d09266

**Comment by prathamesh-sonpatki** [comment]
Thanks, will you release new version ?

On Tuesday 26 January 2016, Stas Spiridonov notifications@github.com
wrote:

> Merged #2 https://github.com/spiridonov/freyja/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spiridonov/freyja/pull/2#event-526302592.

## 

./prathamesh
 GITHUB https://github.com/prathamesh-sonpatki Blog
http://prathamesh-sonpatki.github.com

**Comment by spiridonov** [comment]
@prathamesh-sonpatki already released 0.0.6

**Comment by prathamesh-sonpatki** [comment]
Awesome! Thanks :)

On Tuesday 26 January 2016, Stas Spiridonov notifications@github.com
wrote:

> @prathamesh-sonpatki https://github.com/prathamesh-sonpatki already
> released 0.0.6
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spiridonov/freyja/pull/2#issuecomment-174993662.

## 

./prathamesh
 GITHUB https://github.com/prathamesh-sonpatki Blog
http://prathamesh-sonpatki.github.com

**Pull request merged**
